export default defineAppConfig({
  
  ui: {
    colors: {
      primary: "purple",
      neutral: "neutral",
      amber: "amber",
      red: "red",
      green: "green",
      blue: "blue",
      yellow: "yellow",
      orange: "orange",
      sky: "sky",
      teal: "teal",
      indigo: "indigo",
      emerald: "emerald",
      cyan: "cyan",
      lime: "lime",
      violet: "violet",
      purple: "purple",
      fuchsia: "fuchsia",
      pink: "pink",
      rose: "rose",
      amethyst: "amethyst",
      slate: "slate",
      zinc: "zinc",
      gray: "gray",
      stone: "stone",
      white: "white",
    },
  },
});
