<!-- components/inventory/SupplierModal.vue -->
<script setup lang="ts">
export interface Supplier {
  id: string;
  name: string;
  code: string;
  contactPerson: string;
  email: string;
  phone: string;
  address: string;
  paymentTerms?: string;
  leadTimeDays?: number;
  notes?: string;
  status: "active" | "inactive";
  productIds: string[];
}

export interface SupplierFormData {
  name: string;
  code: string;
  contactPerson: string;
  email: string;
  phone: string;
  address: string;
  paymentTerms: string;
  leadTimeDays: number;
  notes: string;
}

interface Props {
  supplier?: Supplier | null;
  loading?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  supplier: null,
  loading: false,
});

const open = defineModel<boolean>("open", { default: false });

const emit = defineEmits<{
  save: [data: SupplierFormData, isEdit: boolean];
}>();

const { t } = useI18n();

const supplierForm = ref<SupplierFormData>({
  name: "",
  code: "",
  contactPerson: "",
  email: "",
  phone: "",
  address: "",
  paymentTerms: "",
  leadTimeDays: 7,
  notes: "",
});

// Reset form when modal opens or supplier changes
watch([open, () => props.supplier], ([isOpen, supplier]) => {
  if (isOpen) {
    if (supplier) {
      supplierForm.value = {
        name: supplier.name,
        code: supplier.code,
        contactPerson: supplier.contactPerson,
        email: supplier.email,
        phone: supplier.phone,
        address: supplier.address,
        paymentTerms: supplier.paymentTerms || "",
        leadTimeDays: supplier.leadTimeDays || 7,
        notes: supplier.notes || "",
      };
    } else {
      supplierForm.value = {
        name: "",
        code: "",
        contactPerson: "",
        email: "",
        phone: "",
        address: "",
        paymentTerms: "",
        leadTimeDays: 7,
        notes: "",
      };
    }
  }
});

const handleSave = () => {
  emit("save", { ...supplierForm.value }, !!props.supplier);
};

const isEdit = computed(() => !!props.supplier);
</script>

<template>
  <UModal v-model:open="open">
    <template #content>
      <UCard>
        <template #header>
          <h3 class="text-lg font-medium">
            {{
              isEdit ? t("inventory.editSupplier") : t("inventory.addSupplier")
            }}
          </h3>
        </template>

        <div class="space-y-4">
          <div class="grid grid-cols-2 gap-4">
            <UFormField :label="t('inventory.supplierName')" required>
              <UInput
                v-model="supplierForm.name"
                :placeholder="t('inventory.enterSupplierName')"
                class="w-full"
              />
            </UFormField>
            <UFormField :label="t('inventory.supplierCode')">
              <UInput
                v-model="supplierForm.code"
                :placeholder="t('inventory.autoGenerated')"
                class="w-full"
              />
            </UFormField>
          </div>

          <UFormField :label="t('inventory.contactPerson')">
            <UInput
              v-model="supplierForm.contactPerson"
              :placeholder="t('inventory.enterContactPerson')"
              class="w-full"
            />
          </UFormField>

          <div class="grid grid-cols-2 gap-4">
            <UFormField :label="t('common.email')">
              <UInput
                v-model="supplierForm.email"
                type="email"
                class="w-full"
              />
            </UFormField>
            <UFormField :label="t('common.phone')">
              <UInput v-model="supplierForm.phone" type="tel" class="w-full" />
            </UFormField>
          </div>

          <UFormField :label="t('common.address')">
            <UTextarea
              v-model="supplierForm.address"
              :rows="2"
              class="w-full"
            />
          </UFormField>

          <div class="grid grid-cols-2 gap-4">
            <UFormField :label="t('inventory.paymentTerms')">
              <UInput
                v-model="supplierForm.paymentTerms"
                :placeholder="t('inventory.paymentTermsPlaceholder')"
              />
            </UFormField>
            <UFormField :label="t('inventory.leadTime')">
              <UInput
                v-model.number="supplierForm.leadTimeDays"
                type="number"
                min="0"
                class="w-full"
              />
            </UFormField>
          </div>

          <UFormField :label="t('common.notes')">
            <UTextarea v-model="supplierForm.notes" :rows="2" class="w-full" />
          </UFormField>
        </div>

        <template #footer>
          <div class="flex justify-end gap-3">
            <UButton
              color="gray"
              variant="outline"
              :label="t('common.cancel')"
              @click="open = false"
            />
            <UButton
              color="primary"
              :loading="loading"
              :disabled="!supplierForm.name"
              :label="t('common.save')"
              @click="handleSave"
            />
          </div>
        </template>
      </UCard>
    </template>
  </UModal>
</template>
